version: '3.3'
services:
  nginx:
    image: "${REGISTRY_URL}/nginx:latest"
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - dnd
    restart: on-failure

  dnd-server:
    image: "${REGISTRY_URL}/dnd-server:latest"
    container_name: dnd
    networks:
      - dnd
    restart: on-failure

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dnd
    restart: on-failure

networks:
  dnd:
