version: '3.3'
services:
  nginx:
    image: "dlwogns3413/nginx:latest"
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dnd
    depends_on:
      - dnd-server
    restart: on-failure

  dnd-server:
    image: "dlwogns3413/dnd-server:latest"
    container_name: dnd
    volumes:
      - /var/log/dnd:/app/logs
    networks:
      - dnd
    restart: on-failure

  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - /data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - dnd
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  dnd:
