server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8080
spring:
  profiles:
    active: local
    include: secret
jwt:
  secretKey: '${custom.jwt.secretKey}'
  access-token-expire-time: 1800000 # 30분
  refresh-token-expire-time: 86400000 # 1일 (24시간)

# S3 설정
cloud:
  aws:
    credentials:
      accessKey: '${accessKey}'
      secretKey: '${secretKey}'
    s3:
      bucketName: '${bucketName}'
    region:
      static: ap-northeast-2
    stack:
      auto: false

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: dev
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  data:
    redis:
      host: '${custom.redis.host}'
      port: '${custom.redis.port}'

---
spring:
  config:
    activate:
      on-profile: staging
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  flyway:
    enabled: false
  datasource:
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  data:
    redis:
      host: '${custom.redis.host}'
      port: '${custom.redis.port}'

---
spring:
  config:
    activate:
      on-profile: local
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  data:
    redis:
      host: '${custom.redis.host}'
      port: '${custom.redis.port}'

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: h2
    password:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secretKey: ghdsjkghjksdhdawuidhkjasbfhjkxvbjhsdgvjkafjawoldjkawopdjawpdjawpidj
  access-token-expire-time: 1800000 # 30분
  refresh-token-expire-time: 3600000 # 1시간


