server:
  port: 8080
spring:
  profiles:
    active: dev
    include: secret

---
spring:
  config:
    activate:
      on-profile: dev
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  datasource:
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  data:
    redis:
      host: '${custom.redis.host}'
      port: '${custom.redis.port}'

jwt:
  secretKey: '${custom.jwt.secretKey}'
  access-token-expire-time: 1800000 # 30분
  refresh-token-expire-time: 3600000 # 1시간

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: h2
    password:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

jwt:
  secretKey: ghdsjkghjksdhdawuidhkjasbfhjkxvbjhsdgvjkafjawoldjkawopdjawpdjawpidj
  access-token-expire-time: 1800000 # 30분
  refresh-token-expire-time: 3600000 # 1시간

